---

- name: Create LazyLibrarian directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ lazylibrarian_config_directory }}"
    - "{{ lazylibrarian_books_directory }}"
    - "{{ lazylibrarian_download_directory }}"

- name: Set Docker container parameters
  set_fact:
    lazylibrarian_container_parameters:
      name: "{{ lazylibrarian_name }}"
      image: "{{ lazylibrarian_image }}"
      state: started
      published_ports: "{{ lazylibrarian_ports }}"
      volumes:
        - "{{ lazylibrarian_config_directory }}:/config"
        - "{{ lazylibrarian_books_directory }}:/books"
        - "{{ lazylibrarian_download_directory }}:/downloads"
      env: "{{ lazylibrarian_environment_variables }}"

- name: Create LazyLibrarian container
  docker_container: "{{ lazylibrarian_container_parameters | combine(lazylibrarian_docker_additional_options) }}"
  register: lazylibrarian_container

- name: Wait for LazyLibrarian config file
  wait_for:
    path: "{{ lazylibrarian_config_directory }}/config.ini"

- name: Configure LazyLibrarian
  ini_file:
    path: "{{ lazylibrarian_config_directory }}/config.ini"
    section: "{{ item.key.split('.')[0] }}"
    option: "{{ item.key.split('.')[1] }}"
    value: "{{ item.value }}"
  loop: "{{ lookup('dict', lazylibrarian_config) }}"
  notify: Restart LazyLibrarian
